### ISSUE TITLE
Server communication

### ISSUE THREAD

**Issue by gustavung** [Guaschman/Graphrec#4]
We need to be able to send the taken picture to the ML server.

**Comment by Matlar** [comment]
My suggestion is to use the java standard libraries `URL` and `HttpURLConnection` to handle the POST requests, as we are not doing anything complicated. Otherwise you could take a look at [Apache's HTTPClient](http://hc.apache.org/httpcomponents-client-ga/) or [Google's http client](https://github.com/google/google-http-java-client)

**Comment by gustavung** [comment]
I agree with your suggestion to use ´HttpUrlConnection´, it seems to be the standard way to handle HTTP traffic since [Google deprecated the Apache HTTP client](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client).

**Comment by gustavung** [comment]
Partially fixed in #24

**Comment by Matlar** [comment]
Fixed in #29
